### ISSUE TITLE
gcc和boost的问题

### ISSUE THREAD

**Issue by 752525721** [solopointer/thunder-trader#11]
大神，对于初步了解Linux的用户，在安装gcc和boost的时候，按照百度搜索的来进行安装，总是不能把环境配置好，也就无法体验大神的杰作。我想如果大神能够花费一些时间写篇博客教Linux初学者配置gcc和boost，这将是一件值得我们感激的事情！
http://www.huyifeng.net/HFT-prepare.html
参照大神博客中的方法，gcc安装之后，好像make的时候也不能正常工作，大神在博客中提到的boost安装，也只是看到标题，不情之请，请海涵！

**Comment by solopointer** [comment]
boost安装方法已经在http://www.huyifeng.net/HFT-prepare.html更新，感谢支持～

**Comment by 752525721** [comment]
感谢大神回复，有没有QQ群或者微信群之类的？
