### ISSUE TITLE
cmake时候遇到个小问题

### ISSUE THREAD

**Issue by lusic2018** [solopointer/thunder-trader#12]
cmake时候遇到个小问题，提示：which is not an exiting directory.
![22](https://user-images.githubusercontent.com/35355763/50384215-e2e9a900-06fc-11e9-93e7-2b89afa3eacf.jpg)

**Comment by solopointer** [comment]
This bug is caused by the absolute path in the CMakeLists.txt file. Thank you for telling me about this bug. I have fixed it, please git add&commit&pull  and remake it.
