### ISSUE TITLE
monitor.sln build error

### ISSUE THREAD

**Issue by Teddy-Zhu** [solopointer/thunder-trader#13]
platform : win10
tools: vs 2015 , boost 1.58
thunder-trader :   f75e00088cd3bb2ebc3bfee76b735d0211d70135 (发issue时最新版)
error screenshot
![image](https://user-images.githubusercontent.com/9956097/50439879-aa311600-092e-11e9-9a19-bf5d8b766b2e.png)

没办法办法编译成exe

尝试引入common的 StrategyData.h 还是报错

**Comment by solopointer** [comment]
1.保持原始文件的目录层次结构，因为monitor用到了$(SolutionDir)\..\common
2.检查项目配置，是否有把$(SolutionDir)\..\common 加入到Include列表
3.清理之前生成的临时文件，做rebuild

这样试试

**Comment by Teddy-Zhu** [comment]
感觉! 问题解决
