### ISSUE TITLE
Strategy component - experiment

### ISSUE THREAD

**Issue by andrewcz** [solopointer/thunder-trader#14]
Hi @solopointer 
Really excited about the project.
Aspiring developer living in Australia.
Was just wondering when the strategy component may be released.
Hope you're well.
Best,
Andrew

**Comment by solopointer** [comment]
Think you~

This project include two available demo strategies.

https://github.com/solopointer/thunder-trader/tree/master/strategies

One is a pure demo strategy and another is a real arbitrage strategy which is running online.

**Comment by andrewcz** [comment]
Hi @solopointer!
Thank you!
So the strategy research platform is already operational in the project?
Best and kind regards,
Andrew

**Comment by solopointer** [comment]
Yes, it will coming soon~

**Comment by andrewcz** [comment]
Amazing!! Thank you so much!!
Super generous 😀.
Appreciate the guidance.
Best,
Andrew
