### ISSUE TITLE
配置好环境后，先运行哪个文件的呢

### ISSUE THREAD

**Issue by lusic2018** [solopointer/thunder-trader#2]
您好，配置好基本环境 (gcc 7.2; boost 1.68.0; centos7)后，用什么软件或者工具 先运行或者先编译哪个文件的呢？

**Comment by lusic2018** [comment]
![_20181118115631](https://user-images.githubusercontent.com/35355763/48668462-24e56500-eb29-11e8-9bde-be3e4c9edf10.jpg)
![_20181118115712](https://user-images.githubusercontent.com/35355763/48668463-2adb4600-eb29-11e8-84eb-c395b7d9d4e5.jpg)

**Comment by lusic2018** [comment]
gcc版本是 4.8.5 ，理论上应该支持C++11 了哦

**Comment by solopointer** [comment]
看截图猜测可能是gcc4.8对代码所需c++11特征支持不是特别好。系统是在gcc7上面测试通过的，gcc4.8目前正在测试中。
如果编译成功了，可以直接按照README中的方式运行trader-server。
目前代码库中只包含trader-server部分的代码和部分文档。
客户端&实验平台代码和文档正在整理当中，稍后会有commit

**Comment by solopointer** [comment]
> gcc版本是 4.8.5 ，理论上应该支持C++11 了哦

已经push支持了gcc4.8.4，可以pull下来试一试

**Comment by lusic2018** [comment]
@solopointer 还有个小问题，这个路径好像有点问题的...  注：thunder-trader 的目录为/home/admin/gpxt/thunder-trader 
![0](https://user-images.githubusercontent.com/35355763/48780500-093eb200-ed15-11e8-9f1b-74b8a409bdd6.PNG)

**Comment by solopointer** [comment]
![thunder-trader-make](https://user-images.githubusercontent.com/7790193/48816826-b4d01c80-ed7e-11e8-9aa9-483fb25d5852.jpg)

@lusic2018

**Comment by lusic2018** [comment]
> ![thunder-trader-make](https://user-images.githubusercontent.com/7790193/48816826-b4d01c80-ed7e-11e8-9aa9-483fb25d5852.jpg)
> 
> @lusic2018

@solopointer  后面那段数字怎么来的呢？
1Run.SystemNumber=1 [20181021T062516.546639]
![11](https://user-images.githubusercontent.com/35355763/48818195-0ed3e080-ed85-11e8-8df6-c651632ce049.PNG)

**Comment by solopointer** [comment]
> > ![thunder-trader-make](https://user-images.githubusercontent.com/7790193/48816826-b4d01c80-ed7e-11e8-9aa9-483fb25d5852.jpg)
> > @lusic2018
> 
> @solopointer 后面那段数字怎么来的呢？
> 1Run.SystemNumber=1 [20181021T062516.546639]
> ![11](https://user-images.githubusercontent.com/35355763/48818195-0ed3e080-ed85-11e8-8df6-c651632ce049.PNG)

SystemNumber 是自定义的，只要保证在同一台机器上运行的不同thunder-trader进程SystemNumber不同即可

**Comment by lusic2018** [comment]
SystemNumber 是自定义的，好像不行的哦 
![111](https://user-images.githubusercontent.com/35355763/48824660-d988bc00-ed9f-11e8-92ae-e237a2183d15.jpg)

**Comment by solopointer** [comment]
> SystemNumber 是自定义的，好像不行的哦
> ![111](https://user-images.githubusercontent.com/35355763/48824660-d988bc00-ed9f-11e8-92ae-e237a2183d15.jpg)

pull一下&&命令中不需要加Run.SystemNumber=1
