### ISSUE TITLE
Monitor中添加行情源时 出现添加不了的问题，总是报错

### ISSUE THREAD

**Issue by XavierXia** [solopointer/thunder-trader#21]
现象如下：
![image](https://user-images.githubusercontent.com/6349081/57510688-fe66f080-7339-11e9-95dc-e2e695fad410.png)

大神帮忙看看，谢谢！

**Comment by solopointer** [comment]
这个是老版本Monitor，已经停止维护，请切换到新版的WebMonitor

**Comment by XavierXia** [comment]
好的，多谢！
