### ISSUE TITLE
配置文件是具体哪个文件的呢 谢谢 

### ISSUE THREAD

**Issue by lusic2018** [solopointer/thunder-trader#3]
配置文件是thunder-trader-master 里边具体哪个文件的呢 谢谢 
![0](https://user-images.githubusercontent.com/35355763/48975628-2fb37300-f0b0-11e8-9a88-89c8ac1498eb.PNG)

**Comment by solopointer** [comment]
就是你截图的这些内容，就是配置文件的内容

**Comment by lusic2018** [comment]
把thunder-trader文件放在远程服务器上跑，下面这个MainServer的IP是指所放文件的远程服务器的IP的吧，这个不需要输入密码的么？
![00](https://user-images.githubusercontent.com/35355763/48980970-b7c66680-f10a-11e8-9062-6b69ef943f9b.PNG)
