### ISSUE TITLE
好像少某些库的呢 

### ISSUE THREAD

**Issue by lusic2018** [solopointer/thunder-trader#4]
新配置云端服务器，环境配置为gcc 8.2.0 、  boost 1.6.1、centos7.1，cmake的时候没有出现问题，当make 的时候，出现了 collect2: error: ld returned 1 exit status，如下图，请指教...
![bug1](https://user-images.githubusercontent.com/35355763/49022266-6633df80-f1cf-11e8-9b5e-399e0bb5903e.PNG)

**Comment by solopointer** [comment]
1.确保pull到了最新版本
2.确保cmake时正确的找到了boost的路径，cmake从常见系统路径寻找boost，例如/usr/local。
   如果没有找到，则需要手动修改CMakeLists.txt 设置boost include&&lib 路径
