### ISSUE TITLE
Monitor什么时候出来？会开源吗？请大神回复

### ISSUE THREAD

**Issue by 752525721** [solopointer/thunder-trader#5]
Monitor什么时候出来？会开源吗？请大神回复

**Comment by solopointer** [comment]
> Monitor什么时候出来？会开源吗？请大神回复

monitor和research都会开源，现在基本已经开发完成，因为这两个是visual studio项目，所以整理上传比较麻烦一些

**Comment by ssh352** [comment]
visual studio项目意味着只能在windows运行吗？ 强烈支持这个项目～@solopointer

**Comment by solopointer** [comment]
> visual studio项目意味着只能在windows运行吗？ 强烈支持这个项目～@solopointer

是的，因为monitor和research都需要进行数据的展示，windows的图形界面比较适合一些

**Comment by 752525721** [comment]
大神，有时间表吗？

**Comment by solopointer** [comment]
> 大神，有时间表吗？

我尽量加快
