### ISSUE TITLE
大神，有没有策略Demo，帮忙写个策略Demo，好让我们这些菜鸟照葫芦画瓢啊，多谢大神！

### ISSUE THREAD

**Issue by 752525721** [solopointer/thunder-trader#9]
大神，有没有策略Demo，帮忙写个策略Demo，好让我们这些菜鸟照葫芦画瓢啊，多谢大神！
或者写个文档教我们怎么用程序中的那些变量和结构来实现策略，多谢大神！

**Comment by solopointer** [comment]
https://github.com/solopointer/thunder-trader/tree/master/strategies/simple_strategy
